# ReMap Development Environment
# This docker-compose.yml creates our backend services for consistent development
# across all team members regardless of their operating system

version: '3.8'

services:
  # PostgreSQL Database Service
  # This container provides our development database that all team members will share
  postgres:
    image: postgres:17-alpine    # Using PostgreSQL 17 with lightweight Alpine Linux
    container_name: remap-postgres
    restart: unless-stopped      # Automatically restart if container crashes
    
    # Environment variables configure the database
    environment:
      # These create the initial database and user credentials
      POSTGRES_DB: remap_dev          # Name of the database for our app
      POSTGRES_USER: remap_user       # Database username for our application
      POSTGRES_PASSWORD: dev_password # Password (this is for development only!)
      POSTGRES_HOST_AUTH_METHOD: md5  # Authentication method for connections
    
    # Port mapping allows access from host machine and other containers
    ports:
      - "5432:5432"    # Maps container port 5432 to host port 5432
    
    # Volume ensures database data persists when container restarts
    volumes:
      - postgres_data:/var/lib/postgresql/data    # Named volume for data persistence
      # Note: We'll add initialization scripts later when we need them
    
    # Health check ensures database is ready before other services start
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remap_user -d remap_dev"]
      interval: 30s      # Check every 30 seconds
      timeout: 10s       # Wait up to 10 seconds for response
      retries: 5         # Try 5 times before marking as unhealthy
      start_period: 30s  # Wait 30 seconds before starting health checks

# Named volumes for data persistence
# This ensures your database data survives container restarts
volumes:
  postgres_data:
    driver: local

# Networks for service communication
# This creates an isolated network for our services to communicate securely
networks:
  default:
    name: remap-network
    