# ReMap Development Environment
# This docker-compose.yml creates our backend services for consistent development
# across all team members regardless of their operating system

version: '3.8'

services:
  # Express.js Backend Service
  # This container runs our Node.js backend API that connects frontend to database
  backend:
    build:
      context: ./backend           # Build from the backend directory
      dockerfile: Dockerfile       # Use the Dockerfile in backend folder
    container_name: remap-backend
    restart: unless-stopped        # Automatically restart if container crashes
    
    # Port mapping exposes our API to the host machine and mobile app
    ports:
      - "3000:3000"               # Maps container port 3000 to host port 3000
    
    # Environment variables for backend configuration
    environment:
      # Database connection settings - these match our PostgreSQL service
      DB_HOST: postgres           # Service name becomes hostname in Docker network
      DB_PORT: 5432              # PostgreSQL default port
      DB_NAME: remap_dev         # Database name from PostgreSQL service
      DB_USER: remap_user        # Database user from PostgreSQL service  
      DB_PASSWORD: dev_password  # Database password from PostgreSQL service
      
      # Node.js environment settings
      NODE_ENV: development      # Enables development features and logging
      PORT: 3000                # Port for Express server to listen on
    
    # Volume mounting allows live code editing without rebuilding container
    volumes:
      - ./backend:/app           # Mount backend code directory into container
      - /app/node_modules        # Prevent overwriting node_modules in container
    
    # Service dependencies ensure database starts before backend
    depends_on:
      postgres:
        condition: service_healthy  # Wait for database health check to pass
    
    # Development command with hot reloading for code changes
    command: npm run dev
    
    # Health check ensures backend API is responding correctly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s              # Check every 30 seconds
      timeout: 10s               # Wait up to 10 seconds for response
      retries: 5                 # Try 5 times before marking as unhealthy
      start_period: 60s          # Wait 60 seconds before starting health checks

  # PostgreSQL Database Service
  # This container provides our development database that all team members will share
  postgres:
    image: postgres:17-alpine    # Using PostgreSQL 17 with lightweight Alpine Linux
    container_name: remap-postgres
    restart: unless-stopped      # Automatically restart if container crashes
    
    # Environment variables configure the database
    environment:
      # These create the initial database and user credentials
      POSTGRES_DB: remap_dev          # Name of the database for our app
      POSTGRES_USER: remap_user       # Database username for our application
      POSTGRES_PASSWORD: dev_password # Password (this is for development only!)
      POSTGRES_HOST_AUTH_METHOD: md5  # Authentication method for connections
    
    # Port mapping allows access from host machine and other containers
    ports:
      - "5432:5432"    # Maps container port 5432 to host port 5432
    
    # Volume ensures database data persists when container restarts
    volumes:
      - postgres_data:/var/lib/postgresql/data    # Named volume for data persistence
      # Note: We'll add initialization scripts later when we need them
    
    # Health check ensures database is ready before other services start
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remap_user -d remap_dev"]
      interval: 30s      # Check every 30 seconds
      timeout: 10s       # Wait up to 10 seconds for response
      retries: 5         # Try 5 times before marking as unhealthy
      start_period: 30s  # Wait 30 seconds before starting health checks

# Named volumes for data persistence
# This ensures your database data survives container restarts
volumes:
  postgres_data:
    driver: local

# Networks for service communication
# This creates an isolated network for our services to communicate securely
networks:
  default:
    name: remap-network
